export const CharacterClass=[
    {
        "classname":"나이트로드",
        "imgsrc":"/classImg/nightlord.webp"

    },
    {
        "classname":"나이트워커",
        "imgsrc":"/classImg/nightwalker.webp"
    },
    {
        "classname":"다크나이트",
        "imgsrc":"/classImg/darkknight.webp"
    },
    {
        "classname":"데몬슬레이어",
        "imgsrc":"/classImg/demonslayer.webp"
    },
    {
        "classname":"데몬어벤져",
        "imgsrc":"/classImg/demonavenger.webp"
    },
    {
        "classname":"듀얼블레이더",
        "imgsrc":"/classImg/dualblader.webp"
    },
    {
        "classname":"라라",
        "imgsrc":"/classImg/lara.webp"
    },
    {
        "classname":"루미너스",
        "imgsrc":"/classImg/luminous.webp"
    },
    {
        "classname":"메르세데스",
        "imgsrc":"/classImg/mercedes.webp"
    },
    {
        "classname":"메카닉",
        "imgsrc":"/classImg/mechanic.webp"
    },
    {
        "classname":"미하일",
        "imgsrc":"/classImg/mihile.webp"
    },
    {
        "classname":"바이퍼",
        "imgsrc":"/classImg/viper.webp"
    },
    {
        "classname":"배틀메이지",
        "imgsrc":"/classImg/battlemage.webp"
    },
    {
        "classname":"보우마스터",
        "imgsrc":"/classImg/bowmaster.webp"
    },
    {
        "classname":"블래스터",
        "imgsrc":"/classImg/blaster.webp"
    },
    {
        "classname":"비숍",
        "imgsrc":"/classImg/blaster.webp"
    },
    {
        "classname":"섀도어",
        "imgsrc":"/classImg/shadower.webp"
    },
    {
        "classname":"소울마스터",
        "imgsrc":"/classImg/soulmaster.webp"
    },
    {
        "classname":"스트라이커",
        "imgsrc":"/classImg/striker.webp"
    },
    {
        "classname":"신궁",
        "imgsrc":"/classImg/marks.webp"
    },
    {
        "classname":"아델",
        "imgsrc":"/classImg/adele.webp"
    },
    {
        "classname":"아란",
        "imgsrc":"/classImg/aran.webp"
    },
    {
        "classname":"아크",
        "imgsrc":"/classImg/ark.webp"
    },
    {
        "classname":"아크메이지(불,독)",
        "imgsrc":"/classImg/arkmagefp.webp"
    },
    {
        "classname":"아크메이지(썬,콜)",
        "imgsrc":"/classImg/arkmagetc.webp"
    },
    {
        "classname":"에반",
        "imgsrc":"/classImg/evan.webp"
    },
    {
        "classname":"엔젤릭버스터",
        "imgsrc":"/classImg/angelicbuster.webp"
    },
    {
        "classname":"와일드헌터",
        "imgsrc":"/classImg/wildhunter.webp"
    },
    {
        "classname":"윈드브레이커",
        "imgsrc":"/classImg/windbreaker.webp"
    },
    {
        "classname":"은월",
        "imgsrc":"/classImg/shade.webp"
    },
    {
        "classname":"일리움",
        "imgsrc":"/classImg/illium.webp"
    },
    {
        "classname":"제논",
        "imgsrc":"/classImg/xenon.webp"
    },
    {
        "classname":"제로",
        "imgsrc":"/classImg/zero.webp"
    },
    {
        "classname":"카데나",
        "imgsrc":"/classImg/cadena.web"
    },
    {
        "classname":"카이저",
        "imgsrc":"/classImg/kaiser.webp"
    },
    {
        "classname":"카인",
        "imgsrc":"/classImg/kain.webp"
    },
    {
        "classname":"칼리",
        "imgsrc":"/classImg/khali.webp"
    },
    {
        "classname":"캐논마스터",
        "imgsrc":"/classImg/cannonmaster.webp"
    },
    {
        "classname":"캡틴",
        "imgsrc":"/classImg/captain.webp"
    },
    {
        "classname":"키네시스",
        "imgsrc":"/classImg/kinesis.webp"
    },
    {
        "classname":"팔라딘",
        "imgsrc":"/classImg/paladin.webp"
    },
    {
        "classname":"패스파인더",
        "imgsrc":"/classImg/pathfinder.webp"
    },
    {
        "classname":"팬텀",
        "imgsrc":"/classImg/phantom.webp"
    },
    {
        "classname":"플레임위자드",
        "imgsrc":"/classImg/flamewizard.webp"
    },
    {
        "classname":"호영",
        "imgsrc":"/classImg/hoyoung.webp"
    },
    {
        "classname":"히어로",
        "imgsrc":"/classImg/hero.webp"
    },
];
