export const union_class_img_data:{[key: string]:{ img: string } } ={
    "나이트로드":{
        img:"/classImg/nightlord.webp"
    },
    "허밋":{
        img:"/classImg/nightlord.webp"
    },
    "나이트워커":{
        img:"/classImg/nightwalker.webp"
    },
    "다크나이트":{
        img:"/classImg/darkknight.webp"
    },
    "버서커":{
        img:"/classImg/darkknight.webp"
    },
    "데몬슬레이어":{
        img:"/classImg/demonslayer.webp"
    },
    "데몬어벤져":{
        img:"/classImg/demonavenger.webp"
    },
    "듀얼블레이더":{
        img:"/classImg/dualblader.webp"
    },
    "슬래셔":{
        img:"/classImg/dualblader.webp"
    },
    "라라":{
        img:"/classImg/lara.webp"
    },
    "루미너스":{
        img:"/classImg/luminous.webp"
    },
    "메르세데스":{
        img:"/classImg/mercedes.webp"
    },
    "메카닉":{
        img:"/classImg/mechanic.webp"
    },
    "미하일":{
        img:"/classImg/mihile.webp"
    },
    "바이퍼":{
        img:"/classImg/viper.webp"
    },
    "버커니어":{
        img:"/classImg/viper.webp"
    },
    "배틀메이지":{
        img:"/classImg/battlemage.webp"
    },
    "보우마스터":{
        img:"/classImg/bowmaster.webp"
    },
    "레인저":{
        img:"/classImg/bowmaster.webp"
    },
    "블래스터":{
        img:"/classImg/blaster.webp"
    },
    "비숍":{
        img:"/classImg/bishop.webp"
    },
    "프리스트":{
        img:"/classImg/bishop.webp"
    },
    "섀도어":{
        img:"/classImg/shadower.webp"
    },
    "시프마스터":{
        img:"/classImg/shadower.webp"
    },
    "소울마스터":{
        img:"/classImg/soulmaster.webp"
    },
    "스트라이커":{
        img:"/classImg/striker.webp"
    },
    "신궁":{
        img:"/classImg/marks.webp"
    },
    "저격수":{
        img:"/classImg/marks.webp"
    },
    "아델":{
        img:"/classImg/adele.webp"
    },
    "아란":{
        img:"/classImg/aran.webp"
    },
    "아크":{
        img:"/classImg/ark.webp"
    },
    "아크메이지(불,독)":{
        img:"/classImg/arkmagefp.webp"
    },
    "메이지(불,독)":{
        img:"/classImg/arkmagefp.webp"
    },
    "아크메이지(썬,콜)":{
        img:"/classImg/arkmagetc.webp"
    },
    "메이지(썬,콜)":{
        img:"/classImg/arkmagetc.webp"
    },
    "에반":{
        img:"/classImg/evan.webp"
    },
    "엔젤릭버스터":{
        img:"/classImg/angelicbuster.webp"
    },
    "와일드헌터":{
        img:"/classImg/wildhunter.webp"
    },
    "윈드브레이커":{
        img:"/classImg/windbreaker.webp"
    },
    "은월":{
        img:"/classImg/shade.webp"
    },
    "일리움":{
        img:"/classImg/illium.webp"
    },
    "제논":{
        img:"/classImg/xenon.webp"
    },
    "제로":{
        img:"/classImg/zero.webp"
    },
    "카데나":{
        img:"/classImg/cadena.webp"
    },
    "카이저":{
        img:"/classImg/kaiser.webp"
    },
    "카인":{
        img:"/classImg/kain.webp"
    },
    "칼리":{
        img:"/classImg/khali.webp"
    },
    "캐논마스터":{
        img:"/classImg/cannonmaster.webp"
    },
    "캐논블래스터":{
        img:"/classImg/cannonmaster.webp"
    },
    "캡틴":{
        img:"/classImg/captain.webp"
    },
    "발키리":{
        img:"/classImg/captain.webp"
    },
    "팔라딘":{
        img:"/classImg/paladin.webp"
    },
    "나이트":{
        img:"/classImg/paladin.webp"
    },
    "패스파인더":{
        img:"/classImg/pathfinder.webp"
    },
    "체이서":{
        img:"/classImg/pathfinder.webp"
    },
    "팬텀":{
        img:"/classImg/phantom.webp"
    },
    "플레임위자드":{
        img:"/classImg/flamewizard.webp"
    },
    "호영":{
        img:"/classImg/hoyoung.webp"
    },
    "히어로":{
        img:"/classImg/hero.webp"
    },
    "크루세이더":{
        img:"/classImg/hero.webp"
    },
    "키네시스":{
        img:"/classImg/kinesis.webp"
    },
    "모바일 캐릭터":{
        img:"/classImg/MapleM.webp"
    }
}



